# Generated by Django 4.1.4 on 2023-01-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_Name', models.CharField(max_length=50)),
                ('M_Mobile', models.CharField(max_length=50)),
                ('M_Email', models.CharField(max_length=50)),
                ('M_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(max_length=50)),
                ('S_Mobile', models.CharField(max_length=50)),
                ('S_Email', models.CharField(max_length=50)),
                ('S_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Left', models.CharField(max_length=30)),
                ('Operation', models.CharField(max_length=30)),
                ('Right', models.CharField(max_length=30)),
                ('Status', models.BooleanField(default=False)),
                ('Students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterStudentApp.student')),
            ],
        ),
    ]
